import EO from 'ember-orbit/main';
import Store from 'ember-orbit/store';
import Model from 'ember-orbit/model';
import RecordArrayManager from 'ember-orbit/record-array-manager';
import Schema from 'ember-orbit/schema';
import Source from 'ember-orbit/source';
import key from 'ember-orbit/fields/key';
import attr from 'ember-orbit/fields/attr';
import hasMany from 'ember-orbit/fields/has-many';
import hasOne from 'ember-orbit/fields/has-one';
import HasManyArray from 'ember-orbit/links/has-many-array';
import HasOneObject from 'ember-orbit/links/has-one-object';
import LinkProxyMixin from 'ember-orbit/links/link-proxy-mixin';
import FilteredRecordArray from 'ember-orbit/record-arrays/filtered-record-array';
import RecordArray from 'ember-orbit/record-arrays/record-array';

EO.Store = Store;
EO.Model = Model;
EO.RecordArrayManager = RecordArrayManager;
EO.Schema = Schema;
EO.Source = Source;
EO.key = key;
EO.attr = attr;
EO.hasOne = hasOne;
EO.hasMany = hasMany;
EO.HasManyArray = HasManyArray;
EO.HasOneObject = HasOneObject;
EO.LinkProxyMixin = LinkProxyMixin;
EO.FilteredRecordArray = FilteredRecordArray;
EO.RecordArray = RecordArray;

export default EO;
