export { default as SchemaFactory } from './-private/factories/schema-factory';
export { default as CoordinatorFactory } from './-private/factories/coordinator-factory';
export { default as KeyMapFactory } from './-private/factories/key-map-factory';
export { default as attr } from './-private/fields/attr';
export { default as hasMany } from './-private/fields/has-many';
export { default as hasOne } from './-private/fields/has-one';
export { default as key } from './-private/fields/key';
export { default as Cache } from './-private/cache';
export { default as Model } from './-private/model';
export { default as Store } from './-private/store';
// Provide `belongsTo` as an alias to `hasOne`
export { default as belongsTo } from './-private/fields/has-one';
